#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to lint and format changed files, but allow warnings
export ESLINT_IGNORE_WARNINGS=true
npx lint-staged || echo "Warnings found but allowing commit"
