name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './package.json'

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Check for formatting changes
        run: |
          if git diff --name-only | grep -q "." ; then
            echo "::error::Formatting changes detected. Please commit formatted files."
            git diff
            exit 1
          fi

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Regression Tests
        run: npm run test:regression

      - name: Run benchmarks
        run: npm run test:benchmark
